# Generated by Django 5.2.7 on 2025-10-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filter',
            field=models.CharField(default='', max_length=10),
        ),
    ]
